name: WebApp
    version: 1.0.0
    summary: Azure Web App Environment
    description: Deploys a web app in Azure without a datastore
    runner: "lwterraform.azurecr.io/terraform:demo"
    templatePath: webapp.tf
