name: LinuxWebApp
version: 1.0.0
summary: Azure Linux Web App Environment
description: Deploys a web app in Azure without a datastore
runner: "lwtfacr2.azurecr.io/terraform:demo"
templatePath: webapptf2.tf
