name: LinuxWebApp
    version: 1.0.0
    summary: Azure Linux Web App Environment
    description: Deploys a web app in Azure without a datastore
    runner: "lwterraformacr.azurecr.io/terraform:demo"
    templatePath: webapp.tf
